<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Recrovit.RecroGridFramework.Core</RootNamespace>
    <AssemblyName>Recrovit.RecroGridFramework.Core</AssemblyName>
    <RGFBaseDbContext>false</RGFBaseDbContext>
    <RGFCustomSql>false</RGFCustomSql>
  </PropertyGroup>

  <PropertyGroup>
    <Version>10.3.0</Version>
    <FileVersion>$(Version).1$([System.DateTime]::Now.ToString('MMdd'))</FileVersion>
    <InformationalVersion>$(FileVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\rgf-legacy\src\RGF.csproj" Condition="'$(Configuration)'=='Debug'" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(LocalRecrovitAi)')">
    <ProjectReference Include="$(LocalRecrovitAi)" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(LocalRgfLegacy)')">
    <ProjectReference Include="$(LocalRgfLegacy)" />
  </ItemGroup>

  <ItemGroup Condition="!Exists('$(LocalRgfLegacy)')">
    <PackageReference Include="RecroGrid" Version="10.3.0" Condition="'$(Configuration)'=='Release'" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.gitignore" />
    <None Include="..\Directory.Build.props" />
  </ItemGroup>

</Project>
