<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Recrovit.RecroGridFramework.Core</RootNamespace>
    <AssemblyName>Recrovit.RecroGridFramework.Core</AssemblyName>
    <RGFBaseDbContext>false</RGFBaseDbContext>
    <RGFCustomSql>false</RGFCustomSql>
  </PropertyGroup>

  <PropertyGroup>
    <Version>10.3.0</Version>
    <FileVersion>$(Version).1$([System.DateTime]::Now.ToString('MMdd'))</FileVersion>
    <InformationalVersion>$(FileVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <!--<ItemGroup Condition="Exists('$(LocalRecrovitAi)')">
    <ProjectReference Include="$(LocalRecrovitAi)" />
  </ItemGroup>

  <ItemGroup Condition="!Exists('$(LocalRecrovitAi)')">
    <PackageReference Include="Recrovit.AI.Runtime" Version="10.0.0" />
  </ItemGroup>-->

  <ItemGroup>
    <ProjectReference Include="..\..\recrovit-ai\src\Recrovit.AI.Runtime\Recrovit.AI.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(LocalRgfLegacy)')">
    <ProjectReference Include="$(LocalRgfLegacy)" />
  </ItemGroup>

  <ItemGroup Condition="!Exists('$(LocalRgfLegacy)')">
    <PackageReference Include="RecroGrid" Version="10.4.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.gitignore" />
    <None Include="..\Directory.Build.props" />
  </ItemGroup>

</Project>
